# Zhifeng's Player Cards Data Cleaning Notebook

date: y2025m01d11

---

In [5]:
import pandas as pd

In [6]:
V0_COL_SCENARIO_ID = "scenario_id"
V0_COL_GAME_NUM = "scenario_id_1"
V0_COL_INFO_CARD_ID = "info_card_id"
V0_COL_CASE_ID = "case_id"
V0_COL_PLAYER_0_CARDS_ID = "player_0_cards"
V0_COL_PLAYER_1_CARDS_ID = "player_1_cards"

In [7]:
df_v0 = pd.read_csv("player_cards_v0.csv")
df_v0

,id,case_id,scenario_id,info_card_id,scenario_id_1,player_0_cards,player_1_cards
0,1,C1D0a,S1T1,IC1_1,C1_S1,"S1T1C7,S1T1C39,S1T1C24,S1T1C4,S1T1C32,S1T1C37,...","S1T1C16,S1T1C10,S1T1C2,S1T1C31,S1T1C21,S1T1C20..."
1,2,C1D0a,S2T2,IC2_1,C2_S1,"S2T2C12,S2T2C6,S2T2C41,S2T2C14,S2T2C29,S2T2C2,...","S2T2C10,S2T2C30,S2T2C19,S2T2C1,S2T2C34,S2T2C17..."
2,3,C1D0a,S3T3,IC3_1,C3_S1,"S3T3C36,S3T3C18,S3T3C29,S3T3C6,S3T3C41,S3T3C17...","S3T3C23,S3T3C20,S3T3C21,S3T3C11,S3T3C28,S3T3C3..."
3,4,C1D1a,S1T3,IC4_1,C4_S1,"S1T3C2,S1T3C7,S1T3C39,S1T3C30,S1T3C38,S1T3C10,...","S1T3C19,S1T3C27,S1T3C18,S1T3C8,S1T3C4,S1T3C37,..."
4,5,C1D1a,S2T2,IC5_1,C5_S1,"S2T2C24,S2T2C30,S2T2C41,S2T2C29,S2T2C7,S2T2C17...","S2T2C6,S2T2C19,S2T2C13,S2T2C34,S2T2C4,S2T2C20,..."
...,...,...,...,...,...,...,...
103,104,C1D1a,S1T2,IC32_3,C32_S3,"S1T2C10,S1T2C16,S1T2C26,S1T2C31,S1T2C28,S1T2C3...","S1T2C7,S1T2C1,S1T2C4,S1T2C42,S1T2C9,S1T2C13,S1..."
104,105,C1D1a,S2T3,IC33_3,C33_S3,"S2T3C17,S2T3C33,S2T3C2,S2T3C7,S2T3C12,S2T3C41,...","S2T3C36,S2T3C22,S2T3C35,S2T3C28,S2T3C18,S2T3C3..."
105,106,C1D0c,S2T2,IC34_3,C34_S3,"S2T2C12,S2T2C6,S2T2C23,S2T2C19,S2T2C29,S2T2C7,...","S2T2C10,S2T2C25,S2T2C24,S2T2C41,S2T2C14,S2T2C3..."
106,107,C1D0c,S3T2,IC35_3,C35_S3,"S3T2C34,S3T2C13,S3T2C38,S3T2C23,S3T2C29,S3T2C1...","S3T2C35,S3T2C37,S3T2C6,S3T2C39,S3T2C31,S3T2C28..."
107,108,C1D0c,S1T1,IC36_3,C36_S3,"S1T1C13,S1T1C16,S1T1C24,S1T1C31,S1T1C9,S1T1C26...","S1T1C7,S1T1C11,S1T1C21,S1T1C22,S1T1C37,S1T1C34..."

In [8]:
df_v0.sort_values(V0_COL_SCENARIO_ID)

,id,case_id,scenario_id,info_card_id,scenario_id_1,player_0_cards,player_1_cards
0,1,C1D0a,S1T1,IC1_1,C1_S1,"S1T1C7,S1T1C39,S1T1C24,S1T1C4,S1T1C32,S1T1C37,...","S1T1C16,S1T1C10,S1T1C2,S1T1C31,S1T1C21,S1T1C20..."
97,98,C1D1a,S1T1,IC26_3,C26_S3,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
89,90,C1D0c,S1T1,IC18_3,C18_S3,"S1T1C13,S1T1C16,S1T1C24,S1T1C31,S1T1C9,S1T1C26...","S1T1C7,S1T1C11,S1T1C21,S1T1C22,S1T1C37,S1T1C34..."
79,80,C1D1a,S1T1,IC8_3,C8_S3,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
64,65,C1D0b,S1T1,IC29_2,C29_S2,"S1T1C40,S1T1C2,S1T1C11,S1T1C4,S1T1C20,S1T1C3,S...","S1T1C7,S1T1C39,S1T1C16,S1T1C14,S1T1C9,S1T1C21,..."
...,...,...,...,...,...,...,...
84,85,C1D1a,S3T3,IC13_3,C13_S3,"S3T3C36,S3T3C6,S3T3C41,S3T3C38,S3T3C11,S3T3C28...","S3T3C29,S3T3C34,S3T3C23,S3T3C30,S3T3C21,S3T3C1..."
43,44,C1D1a,S3T3,IC8_2,C8_S2,"S3T3C36,S3T3C6,S3T3C41,S3T3C38,S3T3C11,S3T3C28...","S3T3C29,S3T3C34,S3T3C23,S3T3C30,S3T3C21,S3T3C1..."
45,46,C1D0b,S3T3,IC10_2,C10_S2,"S3T3C34,S3T3C20,S3T3C41,S3T3C21,S3T3C17,S3T3C1...","S3T3C36,S3T3C18,S3T3C29,S3T3C23,S3T3C14,S3T3C1..."
26,27,C1D1a,S3T3,IC27_1,C27_S1,"S3T3C36,S3T3C6,S3T3C41,S3T3C38,S3T3C11,S3T3C28...","S3T3C29,S3T3C34,S3T3C23,S3T3C30,S3T3C21,S3T3C1..."
8,9,C1D1a,S3T3,IC9_1,C9_S1,"S3T3C36,S3T3C6,S3T3C41,S3T3C38,S3T3C11,S3T3C28...","S3T3C29,S3T3C34,S3T3C23,S3T3C30,S3T3C21,S3T3C1..."

In [9]:
df_temp = df_v0[(df_v0[V0_COL_SCENARIO_ID] == "S1T2") & (df_v0[V0_COL_CASE_ID] != "C1D1a")]
df_temp

,id,case_id,scenario_id,info_card_id,scenario_id_1,player_0_cards,player_1_cards
9,10,C1D0b,S1T2,IC10_1,C10_S1,"S1T2C7,S1T2C4,S1T2C10,S1T2C11,S1T2C29,S1T2C13,...","S1T2C33,S1T2C1,S1T2C42,S1T2C34,S1T2C30,S1T2C31..."
27,28,C1D0b,S1T2,IC28_1,C28_S1,"S1T2C7,S1T2C4,S1T2C10,S1T2C11,S1T2C29,S1T2C13,...","S1T2C33,S1T2C1,S1T2C42,S1T2C34,S1T2C30,S1T2C31..."
52,53,C1D0c,S1T2,IC17_2,C17_S2,"S1T2C39,S1T2C4,S1T2C42,S1T2C16,S1T2C26,S1T2C21...","S1T2C7,S1T2C33,S1T2C30,S1T2C11,S1T2C31,S1T2C5,..."
70,71,C1D0c,S1T2,IC35_2,C35_S2,"S1T2C39,S1T2C4,S1T2C42,S1T2C16,S1T2C26,S1T2C21...","S1T2C7,S1T2C33,S1T2C30,S1T2C11,S1T2C31,S1T2C5,..."
73,74,C1D0a,S1T2,IC2_3,C2_S3,"S1T2C33,S1T2C1,S1T2C4,S1T2C16,S1T2C38,S1T2C5,S...","S1T2C7,S1T2C42,S1T2C18,S1T2C10,S1T2C29,S1T2C13..."
91,92,C1D0a,S1T2,IC20_3,C20_S3,"S1T2C33,S1T2C1,S1T2C4,S1T2C16,S1T2C38,S1T2C5,S...","S1T2C7,S1T2C42,S1T2C18,S1T2C10,S1T2C29,S1T2C13..."

In [10]:
df_temp.iloc[4][V0_COL_PLAYER_0_CARDS_ID] == df_temp.iloc[5][V0_COL_PLAYER_0_CARDS_ID] and df_temp.iloc[4][V0_COL_PLAYER_1_CARDS_ID] == df_temp.iloc[5][V0_COL_PLAYER_1_CARDS_ID]

True

In [11]:
df_temp = df_v0[(df_v0[V0_COL_SCENARIO_ID] == "S1T1") & (df_v0[V0_COL_CASE_ID] == "C1D1a")]
df_temp

,id,case_id,scenario_id,info_card_id,scenario_id_1,player_0_cards,player_1_cards
12,13,C1D1a,S1T1,IC13_1,C13_S1,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
30,31,C1D1a,S1T1,IC31_1,C31_S1,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
40,41,C1D1a,S1T1,IC5_2,C5_S2,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
58,59,C1D1a,S1T1,IC23_2,C23_S2,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
79,80,C1D1a,S1T1,IC8_3,C8_S3,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."
97,98,C1D1a,S1T1,IC26_3,C26_S3,"S1T1C2,S1T1C24,S1T1C31,S1T1C4,S1T1C21,S1T1C37,...","S1T1C39,S1T1C40,S1T1C16,S1T1C23,S1T1C20,S1T1C3..."

## Cleaning Column `case_id`

It seems that all the `case_id` start with "C1".

It seems there are no cases with `case_id` "C1D1" starts with anything other than "a".

In [12]:
def transform_case_v0_id_str_fn(case_v0_id_str: str):
  CHAR_LOWER_A_U8 = ord('a')
  return (int(case_v0_id_str[1]), int(case_v0_id_str[3]), int(ord(case_v0_id_str[4]) - CHAR_LOWER_A_U8))

assert(transform_case_v0_id_str_fn("C1D1a") == (1,1,0))
assert(transform_case_v0_id_str_fn("C2D2b") == (2,2,1))

# Export to JS

## Parse Things like "S1T1C1"

In [13]:
def transform_scenario_v0_id_str_fn(name_str:str):
  ans_list = [0,0,0]
  parsing_num_flag = False
  num_i = 0
  for c_char in name_str:
    if c_char.isdigit():
      if num_i > 2:
        print(name_str)
      ans_list[num_i] = ans_list[num_i] * 10 + int(c_char)
      parsing_num_flag = True
    else:
      if parsing_num_flag == True:
        parsing_num_flag = False
        num_i += 1

  return (ans_list[0], ans_list[1], ans_list[2])

assert(transform_scenario_v0_id_str_fn("S1T1C1") == (1,1,1))
assert(transform_scenario_v0_id_str_fn("S1T2C2") == (1,2,2))
assert(transform_scenario_v0_id_str_fn("S1T2") == (1,2,0))

## Parse Card Indices String

In [14]:
def transform_card_id_list_str_to_idx_fn(card_id_list_string: str):
  card_id_list = card_id_list_string.split(',')
  card_idx_list = []
  for card_id_str in card_id_list:
    card_idx_list.append(int(transform_scenario_v0_id_str_fn(card_id_str)[2]) - 1) # To Zero Based Index
  card_idx_list.sort()
  return card_idx_list

assert(transform_card_id_list_str_to_idx_fn("S1T1C1,S1T1C2") == [0,1])
assert(transform_card_id_list_str_to_idx_fn("S1T2C1,S1T2C3") == [0,2])

## Parse Game Num Index String

In [15]:
def transform_in_game_num_idx_str_to_idx_fn(game_num_idx_str: str):
  return int(game_num_idx_str[-1]) - 1

assert(transform_in_game_num_idx_str_to_idx_fn("C36_S1") == 0)
assert(transform_in_game_num_idx_str_to_idx_fn("C36_S2") == 1)

In [16]:
def transform_condition_id_str_to_idx_fn(condition_id_str: str):
  ans_condition_i = 0
  met_number_c_flag = False
  for c in condition_id_str:
    if c.isdigit():
      ans_condition_i = ans_condition_i * 10 + int(c)
      met_number_c_flag = True
    elif met_number_c_flag == True:
      break
  return ans_condition_i

assert(transform_condition_id_str_to_idx_fn("C36_S1") == 36)
assert(transform_condition_id_str_to_idx_fn("C35_S2") == 35)

In [19]:
# case d, case variant, scenario id, scenario type, player_0 card indices, player_1 card indices
# info_map = {}
# duplicate_count = 0

info_list = []

for row_idx in range(0,len(df_v0)):
  row = df_v0.iloc[row_idx]
  case_info_tuple = transform_case_v0_id_str_fn(row[V0_COL_CASE_ID])
  scenario_info_tupe = transform_scenario_v0_id_str_fn(row[V0_COL_SCENARIO_ID])
  condition_idx = transform_condition_id_str_to_idx_fn(row[V0_COL_GAME_NUM])
  game_num_idx = transform_in_game_num_idx_str_to_idx_fn(row[V0_COL_GAME_NUM])
  player_0_card_idx_list = transform_card_id_list_str_to_idx_fn(row[V0_COL_PLAYER_0_CARDS_ID])
  player_1_card_idx_list = transform_card_id_list_str_to_idx_fn(row[V0_COL_PLAYER_1_CARDS_ID])
  assert(len(player_0_card_idx_list) == len(player_1_card_idx_list))
  info_list.append([condition_idx, game_num_idx, case_info_tuple[1],case_info_tuple[2], scenario_info_tupe[0], scenario_info_tupe[1], player_0_card_idx_list, player_1_card_idx_list])
  # player_card_id_info = (case_info_tuple[1],case_info_tuple[2], scenario_info_tupe[0], scenario_info_tupe[1], game_num_idx)
  # if not player_card_id_info in info_map.keys():
  #   info_map[player_card_id_info] = (player_0_card_idx_list,player_1_card_idx_list)
  # else:
  #   assert(info_map[player_card_id_info] == (player_0_card_idx_list, player_1_card_idx_list))
  #   duplicate_count += 1

# print(f"Duplicate: {duplicate_count} / {len(df_v0)}")

> CAUTION: It seems there is a "S3T3C31+D1104" in the 8th record  in the original SQL code.

In [21]:
# line_list = []
# for (key, value) in info_map.items():
#   line_list.append(f"[{key[0]},{key[1]},{key[2]},{key[3]},{key[4]},{value[0]},{value[1]}],")

# line_list.sort()

# for line in line_list:
#   print(line)

info_list.sort()

for info in info_list:
  print(info, end=",\n")

[1, 0, 0, 0, 1, 1, [3, 6, 7, 11, 18, 23, 28, 31, 33, 34, 36, 37, 38], [0, 1, 2, 5, 9, 15, 16, 17, 19, 20, 25, 29, 30]],
[1, 1, 0, 0, 2, 1, [2, 8, 10, 11, 12, 13, 15, 16, 18, 23, 25, 29, 34, 38], [1, 3, 9, 20, 26, 27, 28, 30, 31, 33, 36, 37, 39, 40]],
[1, 2, 0, 0, 3, 1, [4, 8, 13, 15, 17, 19, 20, 23, 24, 28, 29, 33, 35, 38, 41], [0, 2, 3, 6, 9, 10, 12, 16, 21, 25, 26, 32, 36, 37, 40]],
[2, 0, 0, 0, 2, 2, [1, 5, 10, 11, 13, 17, 19, 27, 28, 31, 32, 34, 37, 40], [0, 2, 3, 9, 14, 16, 18, 21, 25, 29, 30, 33, 35, 39]],
[2, 1, 0, 0, 3, 2, [0, 2, 11, 13, 16, 19, 21, 22, 23, 33, 34, 38, 40], [1, 3, 4, 6, 9, 10, 15, 18, 24, 25, 27, 30, 37]],
[2, 2, 0, 0, 1, 2, [0, 2, 3, 4, 11, 14, 15, 18, 22, 24, 31, 32, 36, 37], [1, 6, 9, 12, 13, 16, 17, 21, 27, 28, 30, 34, 35, 41]],
[3, 0, 0, 0, 3, 3, [0, 3, 4, 5, 16, 17, 24, 26, 28, 30, 32, 35, 39, 40], [2, 6, 9, 10, 11, 12, 18, 19, 20, 22, 23, 25, 27, 36]],
[3, 1, 0, 0, 1, 3, [1, 3, 8, 9, 11, 13, 14, 15, 16, 18, 19, 25, 31, 34], [4, 12, 17, 22, 23, 24, 27, 30, 32, 33, 36, 37, 38, 39]],
[3, 2, 0, 0, 2, 3, [0, 1, 2, 3, 6, 10, 13, 19, 20, 25, 30, 33, 35, 38], [5, 7, 8, 9, 17, 18, 21, 26, 27, 31, 32, 36, 40, 41]],
[4, 0, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[4, 1, 1, 0, 3, 2, [3, 11, 12, 13, 15, 18, 20, 21, 23, 31, 32, 34, 42], [0, 1, 4, 14, 16, 22, 24, 26, 30, 33, 37, 38, 43]],
[4, 2, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[5, 0, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[5, 1, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[5, 2, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[6, 0, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[6, 1, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[6, 2, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[7, 0, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[7, 1, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[7, 2, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[8, 0, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[8, 1, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[8, 2, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[9, 0, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[9, 1, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[9, 2, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[10, 0, 0, 1, 1, 2, [3, 4, 5, 6, 9, 10, 11, 12, 14, 24, 26, 28, 31, 37], [0, 1, 7, 16, 20, 21, 22, 29, 30, 32, 33, 34, 35, 41]],
[10, 1, 0, 1, 3, 3, [0, 1, 4, 8, 10, 16, 19, 20, 21, 24, 30, 33, 36, 39, 40], [2, 6, 7, 13, 15, 17, 18, 22, 23, 27, 28, 31, 35, 38, 41]],
[10, 2, 0, 1, 2, 1, [2, 6, 8, 9, 11, 15, 16, 17, 32, 34, 35, 37, 38, 40], [1, 3, 4, 5, 13, 21, 23, 26, 27, 28, 29, 33, 36, 39]],
[11, 0, 0, 1, 2, 3, [2, 3, 7, 10, 12, 13, 16, 19, 23, 27, 30, 32, 35, 39], [5, 9, 15, 20, 21, 22, 24, 26, 28, 31, 33, 36, 38, 41]],
[11, 1, 0, 1, 1, 1, [1, 2, 3, 10, 18, 19, 31, 32, 34, 35, 36, 37, 39], [0, 5, 6, 8, 13, 15, 16, 20, 21, 25, 28, 29, 38]],
[11, 2, 0, 1, 3, 2, [0, 3, 6, 9, 11, 13, 14, 20, 21, 22, 24, 32, 43], [7, 15, 16, 18, 19, 25, 27, 28, 31, 33, 36, 37, 40]],
[12, 0, 0, 1, 3, 1, [2, 6, 7, 10, 11, 18, 19, 24, 28, 29, 31, 33, 37, 38, 41], [3, 4, 5, 8, 9, 14, 15, 16, 22, 23, 26, 27, 32, 36, 40]],
[12, 1, 0, 1, 2, 2, [0, 1, 5, 7, 10, 23, 26, 27, 29, 31, 32, 33, 37, 38], [2, 4, 8, 9, 13, 14, 15, 18, 19, 25, 30, 34, 36, 39]],
[12, 2, 0, 1, 1, 3, [3, 5, 6, 8, 9, 10, 14, 25, 26, 31, 34, 36, 38, 39], [4, 11, 12, 16, 17, 18, 21, 22, 24, 28, 30, 32, 33, 35]],
[13, 0, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[13, 1, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[13, 2, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[14, 0, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[14, 1, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[14, 2, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[15, 0, 1, 0, 3, 2, [3, 11, 12, 13, 15, 18, 20, 21, 23, 31, 32, 34, 42], [0, 1, 4, 14, 16, 22, 24, 26, 30, 33, 37, 38, 43]],
[15, 1, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[15, 2, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[16, 0, 0, 2, 1, 3, [1, 2, 3, 4, 10, 13, 14, 17, 24, 25, 28, 29, 32, 37], [0, 5, 6, 8, 11, 12, 15, 19, 20, 21, 22, 30, 31, 34]],
[16, 1, 0, 2, 3, 1, [5, 8, 15, 16, 20, 24, 26, 29, 31, 34, 35, 36, 39, 40], [1, 3, 7, 9, 11, 12, 13, 14, 17, 23, 28, 33, 37, 41]],
[16, 2, 0, 2, 2, 2, [5, 6, 8, 11, 14, 18, 19, 22, 25, 26, 28, 30, 31, 34], [3, 7, 9, 10, 13, 17, 20, 23, 24, 27, 32, 36, 39, 40]],
[17, 0, 0, 2, 2, 1, [0, 1, 2, 4, 6, 16, 18, 24, 25, 27, 28, 31, 33, 34], [3, 7, 8, 10, 12, 15, 21, 22, 23, 26, 32, 35, 38, 39]],
[17, 1, 0, 2, 1, 2, [1, 3, 5, 11, 15, 18, 20, 25, 27, 31, 35, 38, 41], [2, 4, 6, 10, 16, 19, 21, 23, 26, 29, 30, 32, 36]],
[17, 2, 0, 2, 3, 2, [2, 12, 16, 17, 18, 22, 23, 28, 32, 33, 37, 41], [0, 5, 6, 13, 15, 19, 20, 27, 30, 34, 36, 38]],
[18, 0, 0, 2, 3, 2, [2, 12, 16, 17, 18, 22, 23, 28, 32, 33, 37, 41], [0, 5, 6, 13, 15, 19, 20, 27, 30, 34, 36, 38]],
[18, 1, 0, 2, 2, 3, [0, 6, 11, 15, 19, 20, 21, 23, 26, 29, 30, 35, 38, 41], [1, 3, 4, 5, 10, 13, 16, 17, 24, 25, 31, 33, 36, 39]],
[18, 2, 0, 2, 1, 1, [8, 11, 12, 15, 23, 25, 26, 27, 29, 30, 31, 32, 37], [0, 4, 5, 6, 7, 10, 18, 20, 21, 24, 33, 35, 36]],
[19, 0, 0, 0, 1, 1, [3, 6, 7, 11, 18, 23, 28, 31, 33, 34, 36, 37, 38], [0, 1, 2, 5, 9, 15, 16, 17, 19, 20, 25, 29, 30]],
[19, 1, 0, 0, 2, 1, [2, 8, 10, 11, 12, 13, 15, 16, 18, 23, 25, 29, 34, 38], [1, 3, 9, 20, 26, 27, 28, 30, 31, 33, 36, 37, 39, 40]],
[19, 2, 0, 0, 3, 1, [4, 8, 13, 15, 17, 19, 20, 23, 24, 28, 29, 33, 35, 38, 41], [0, 2, 3, 6, 9, 10, 12, 16, 21, 25, 26, 32, 36, 37, 40]],
[20, 0, 0, 0, 2, 2, [1, 5, 10, 11, 13, 17, 19, 27, 28, 31, 32, 34, 37, 40], [0, 2, 3, 9, 14, 16, 18, 21, 25, 29, 30, 33, 35, 39]],
[20, 1, 0, 0, 3, 2, [0, 2, 11, 13, 16, 19, 21, 22, 23, 33, 34, 38, 40], [1, 3, 4, 6, 9, 10, 15, 18, 24, 25, 27, 30, 37]],
[20, 2, 0, 0, 1, 2, [0, 2, 3, 4, 11, 14, 15, 18, 22, 24, 31, 32, 36, 37], [1, 6, 9, 12, 13, 16, 17, 21, 27, 28, 30, 34, 35, 41]],
[21, 0, 0, 0, 3, 3, [0, 3, 4, 5, 16, 17, 24, 26, 28, 30, 32, 35, 39, 40], [2, 6, 9, 10, 11, 12, 18, 19, 20, 22, 23, 25, 27, 36]],
[21, 1, 0, 0, 1, 3, [1, 3, 8, 9, 11, 13, 14, 15, 16, 18, 19, 25, 31, 34], [4, 12, 17, 22, 23, 24, 27, 30, 32, 33, 36, 37, 38, 39]],
[21, 2, 0, 0, 2, 3, [0, 1, 2, 3, 6, 10, 13, 19, 20, 25, 30, 33, 35, 38], [5, 7, 8, 9, 17, 18, 21, 26, 27, 31, 32, 36, 40, 41]],
[22, 0, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[22, 1, 1, 0, 3, 2, [3, 11, 12, 13, 15, 18, 20, 21, 23, 31, 32, 34, 42], [0, 1, 4, 14, 16, 22, 24, 26, 30, 33, 37, 38, 43]],
[22, 2, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[23, 0, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[23, 1, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[23, 2, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[24, 0, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[24, 1, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[24, 2, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[25, 0, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[25, 1, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[25, 2, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[26, 0, 1, 0, 2, 1, [0, 6, 8, 10, 11, 15, 25, 26, 27, 30, 31, 32, 35, 37], [1, 2, 3, 9, 12, 13, 16, 17, 19, 28, 29, 33, 34, 38]],
[26, 1, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[26, 2, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[27, 0, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[27, 1, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[27, 2, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[28, 0, 0, 1, 1, 2, [3, 4, 5, 6, 9, 10, 11, 12, 14, 24, 26, 28, 31, 37], [0, 1, 7, 16, 20, 21, 22, 29, 30, 32, 33, 34, 35, 41]],
[28, 1, 0, 1, 3, 3, [0, 1, 4, 8, 10, 16, 19, 20, 21, 24, 30, 33, 36, 39, 40], [2, 6, 7, 13, 15, 17, 18, 22, 23, 27, 28, 31, 35, 38, 41]],
[28, 2, 0, 1, 2, 1, [2, 6, 8, 9, 11, 15, 16, 17, 32, 34, 35, 37, 38, 40], [1, 3, 4, 5, 13, 21, 23, 26, 27, 28, 29, 33, 36, 39]],
[29, 0, 0, 1, 2, 3, [2, 3, 7, 10, 12, 13, 16, 19, 23, 27, 30, 32, 35, 39], [5, 9, 15, 20, 21, 22, 24, 26, 28, 31, 33, 36, 38, 41]],
[29, 1, 0, 1, 1, 1, [1, 2, 3, 10, 18, 19, 31, 32, 34, 35, 36, 37, 39], [0, 5, 6, 8, 13, 15, 16, 20, 21, 25, 28, 29, 38]],
[29, 2, 0, 1, 3, 2, [0, 3, 6, 9, 11, 13, 14, 20, 21, 22, 24, 32, 43], [7, 15, 16, 18, 19, 25, 27, 28, 31, 33, 36, 37, 40]],
[30, 0, 0, 1, 3, 1, [2, 6, 7, 10, 11, 18, 19, 24, 28, 29, 31, 33, 37, 38, 41], [3, 4, 5, 8, 9, 14, 15, 16, 22, 23, 26, 27, 32, 36, 40]],
[30, 1, 0, 1, 2, 2, [0, 1, 5, 7, 10, 23, 26, 27, 29, 31, 32, 33, 37, 38], [2, 4, 8, 9, 13, 14, 15, 18, 19, 25, 30, 34, 36, 39]],
[30, 2, 0, 1, 1, 3, [3, 5, 6, 8, 9, 10, 14, 25, 26, 31, 34, 36, 38, 39], [4, 11, 12, 16, 17, 18, 21, 22, 24, 28, 30, 32, 33, 35]],
[31, 0, 1, 0, 1, 1, [1, 3, 7, 16, 17, 20, 23, 26, 30, 32, 34, 35, 36], [0, 15, 18, 19, 22, 27, 28, 29, 31, 33, 37, 38, 39]],
[31, 1, 1, 0, 2, 2, [1, 6, 7, 10, 14, 16, 21, 23, 26, 28, 29, 32, 39, 40], [3, 5, 12, 17, 18, 19, 25, 27, 30, 31, 33, 34, 37, 38]],
[31, 2, 1, 0, 3, 3, [1, 3, 4, 5, 8, 9, 10, 18, 21, 27, 35, 37, 39, 40], [0, 2, 12, 16, 20, 22, 24, 28, 29, 30, 31, 32, 33, 41]],
[32, 0, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[32, 1, 1, 0, 3, 1, [4, 7, 9, 10, 11, 13, 19, 20, 21, 26, 28, 31, 39, 41], [6, 8, 12, 15, 16, 17, 18, 24, 29, 30, 33, 36, 38, 40]],
[32, 2, 1, 0, 1, 2, [4, 5, 9, 13, 15, 24, 25, 26, 27, 30, 34, 36, 37], [0, 1, 2, 3, 6, 8, 11, 12, 14, 21, 22, 31, 41]],
[33, 0, 1, 0, 3, 2, [3, 11, 12, 13, 15, 18, 20, 21, 23, 31, 32, 34, 42], [0, 1, 4, 14, 16, 22, 24, 26, 30, 33, 37, 38, 43]],
[33, 1, 1, 0, 1, 3, [1, 4, 5, 6, 8, 9, 10, 19, 22, 27, 29, 31, 37, 38], [3, 7, 14, 15, 16, 17, 18, 24, 25, 26, 30, 32, 34, 36]],
[33, 2, 1, 0, 2, 3, [1, 2, 3, 6, 8, 11, 13, 16, 23, 32, 36, 39, 40, 41], [10, 12, 17, 19, 20, 21, 22, 25, 26, 27, 30, 34, 35, 38]],
[34, 0, 0, 2, 1, 3, [1, 2, 3, 4, 10, 13, 14, 17, 24, 25, 28, 29, 32, 37], [0, 5, 6, 8, 11, 12, 15, 19, 20, 21, 22, 30, 31, 34]],
[34, 1, 0, 2, 3, 1, [5, 8, 15, 16, 20, 24, 26, 29, 31, 34, 35, 36, 39, 40], [1, 3, 7, 9, 11, 12, 13, 14, 17, 23, 28, 33, 37, 41]],
[34, 2, 0, 2, 2, 2, [5, 6, 8, 11, 14, 18, 19, 22, 25, 26, 28, 30, 31, 34], [3, 7, 9, 10, 13, 17, 20, 23, 24, 27, 32, 36, 39, 40]],
[35, 0, 0, 2, 2, 1, [0, 1, 2, 4, 6, 16, 18, 24, 25, 27, 28, 31, 33, 34], [3, 7, 8, 10, 12, 15, 21, 22, 23, 26, 32, 35, 38, 39]],
[35, 1, 0, 2, 1, 2, [1, 3, 5, 11, 15, 18, 20, 25, 27, 31, 35, 38, 41], [2, 4, 6, 10, 16, 19, 21, 23, 26, 29, 30, 32, 36]],
[35, 2, 0, 2, 3, 2, [2, 12, 16, 17, 18, 22, 23, 28, 32, 33, 37, 41], [0, 5, 6, 13, 15, 19, 20, 27, 30, 34, 36, 38]],
[36, 0, 0, 2, 3, 2, [2, 12, 16, 17, 18, 22, 23, 28, 32, 33, 37, 41], [0, 5, 6, 13, 15, 19, 20, 27, 30, 34, 36, 38]],
[36, 1, 0, 2, 2, 3, [0, 6, 11, 15, 19, 20, 21, 23, 26, 29, 30, 35, 38, 41], [1, 3, 4, 5, 10, 13, 16, 17, 24, 25, 31, 33, 36, 39]],
[36, 2, 0, 2, 1, 1, [8, 11, 12, 15, 23, 25, 26, 27, 29, 30, 31, 32, 37], [0, 4, 5, 6, 7, 10, 18, 20, 21, 24, 33, 35, 36]],